import test from 'node:test';
import assert from 'node:assert/strict';
import {sampleDataset,BASKET} from '../public/data.js';
let serial=0;
function response(){return {headers:{},code:200,setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};}
function records(symbols=BASKET){return symbols.flatMap(symbol=>sampleDataset()[symbol].slice(-250).map(r=>({symbol,...r,...Object.fromEntries(['open','high','low','close','volume'].map(k=>['adj_'+k,r[k]]))})));}
async function withProvider(key,fetcher,fn){const previous=process.env.MARKETSTACK_API_KEY,originalFetch=globalThis.fetch;if(key)process.env.MARKETSTACK_API_KEY=key;else delete process.env.MARKETSTACK_API_KEY;globalThis.fetch=fetcher;try{const {default:handler}=await import('../api/history.js?test='+serial++);await fn(handler);}finally{globalThis.fetch=originalFetch;if(previous!==undefined)process.env.MARKETSTACK_API_KEY=previous;else delete process.env.MARKETSTACK_API_KEY;}}
function pages(all){return async url=>{assert.equal(url.origin,'https://api.marketstack.com');assert.equal(url.pathname,'/v2/eod');const offset=+url.searchParams.get('offset');const data=all.slice(offset,offset+1000);return {ok:true,status:200,json:async()=>({data,pagination:{offset,count:data.length,total:all.length}})};};}
test('Marketstack requires configuration without sample fallback',()=>withProvider(null,()=>{throw Error('must not fetch');},async handler=>{const res=response();await handler({query:{symbol:'NVDA'}},res);assert.equal(res.code,503);assert.equal(res.data.code,'provider-not-configured');assert.equal(res.data.dataset,undefined);}));
test('Marketstack paginates eight adjusted assets without exposing credentials',()=>withProvider('test-marketstack-secret',pages(records()),async handler=>{const res=response();await handler({query:{symbol:'NVDA',basket:'1'}},res);assert.equal(res.code,200);assert.equal(Object.keys(res.data.dataset).length,8);assert.equal(res.data.rows.length,250);assert.equal(res.data.source,'marketstack');assert.equal(res.data.adjustment,'all');assert.ok(!JSON.stringify(res.data).includes('test-marketstack-secret'));assert.equal(res.headers['Cache-Control'],'no-store');}));
test('Basket alignment reports dropped observations',()=>withProvider('test-marketstack-secret',pages(records().filter(r=>r.symbol!=='TSLA'||r.date!=='2025-06-30')),async handler=>{const res=response();await handler({query:{symbol:'AAPL',basket:'1'}},res);assert.equal(res.code,200);assert.equal(res.data.rows.length,249);assert.equal(res.data.droppedRows.AAPL,1);assert.equal(res.data.droppedRows.TSLA,0);assert.deepEqual(res.data.dataset.AAPL.map(r=>r.date),res.data.dataset.TSLA.map(r=>r.date));}));
for(const [status,providerCode,expected] of [[401,'invalid_access_key','provider-auth'],[403,'https_access_restricted','provider-plan'],[429,'usage_limit_reached','provider-quota']])test('Provider '+status+' has a safe specific error',()=>withProvider('test-marketstack-secret',async()=>({ok:false,status,json:async()=>({error:{code:providerCode,message:'private test-marketstack-secret'}})}),async handler=>{const res=response();await handler({query:{symbol:'NVDA',basket:'1'}},res);assert.equal(res.code,status);assert.equal(res.data.code,expected);assert.equal(res.data.dataset,undefined);assert.ok(!JSON.stringify(res.data).includes('test-marketstack-secret'));}));
test('Missing adjusted values use a consistently unadjusted dataset with explicit provenance',()=>withProvider('test-marketstack-secret',pages(records(['NVDA']).map((r,i)=>i? r:{...r,adj_open:null})),async handler=>{const res=response();await handler({query:{symbol:'NVDA'}},res);assert.equal(res.code,200);assert.equal(res.data.adjustment,'unadjusted');assert.equal(res.data.rows[0].open,records(['NVDA'])[0].open);}));
test('Insufficient history never commits a partial dataset',()=>withProvider('test-marketstack-secret',pages(records(['NVDA']).slice(0,100)),async handler=>{const res=response();await handler({query:{symbol:'NVDA'}},res);assert.equal(res.code,422);assert.equal(res.data.code,'provider-history');assert.equal(res.data.dataset,undefined);}));
test('Concurrent requests coalesce and later requests use cache',()=>{let calls=0;return withProvider('test-marketstack-secret',async url=>{calls++;return pages(records(['NVDA']))(url);},async handler=>{const a=response(),b=response(),c=response();await Promise.all([handler({query:{symbol:'NVDA'}},a),handler({query:{symbol:'NVDA'}},b)]);await handler({query:{symbol:'NVDA'}},c);assert.equal(calls,1);assert.equal(a.code,200);assert.deepEqual(a.data,b.data);assert.deepEqual(a.data,c.data);});});

test('Insufficient usable bars are rejected without importing null observations',()=>withProvider('test-marketstack-secret',pages(records(['NVDA']).map((r,i)=>i>=100?r:{...r,adj_open:null,open:null})),async handler=>{const res=response();await handler({query:{symbol:'NVDA'}},res);assert.equal(res.code,422);assert.equal(res.data.code,'provider-history');assert.equal(res.data.dataset,undefined);assert.equal(res.data.detail.excludedRows.NVDA,100);}));

test('Null raw observations are excluded and coverage is reported',()=>withProvider('test-marketstack-secret',pages(records(['NVDA']).map((r,i)=>i?r:{...r,adj_open:null,open:null})),async handler=>{const res=response();await handler({query:{symbol:'NVDA'}},res);assert.equal(res.code,200);assert.equal(res.data.rows.length,249);assert.equal(res.data.excludedRows.NVDA,1);assert.equal(res.data.adjustment,'all');}));
